services:
  - type: web
    name: notas-backend
    env: python
    region: oregon
    plan: free
    repo: https://github.com/josephvr13/notasBackend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notas-db
          property: connectionString

  - type: database
    name: notas-db
    plan: free
    region: oregon
    databaseName: notas_db
    user: joseph
    ipAllowList: []
    mysqlVersion: 8

  - type: web
    name: notas-db-initializer
    env: python
    plan: free
    repo: https://github.com/josephvr13/notasBackend
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notas-db
          property: connectionString
